name: AlonsoLeagueRewards
version: 1.3
main: abhigya.alonsoleagueaddon.Main
author: AvengerAK
softdepend: [AlonsoLeagues]
commands:
  leaguerewards:
    description: Basic plugin command
    aliases:
      - lr
      - lreward
      - leaguereward
      - alonsoleaguerewards
      - alonsoleaguereward